# Generated by Django 4.1.7 on 2023-03-12 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_dog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='image',
            field=models.ImageField(default='dogs', upload_to='main_app/static/uploads/'),
        ),
    ]
